# Configurations for containers in Github Actions ci

version: "3.7"

services:
  py-backend:
    container_name: cas_py_backend
    command: ./run-test.sh
    build:
      context: ./backend/python
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    dns:
      - 8.8.8.8
    depends_on:
      - db-test
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_TEST_HOST
      - FIREBASE_SVC_ACCOUNT_PRIVATE_KEY
      - FIREBASE_SVC_ACCOUNT_PRIVATE_KEY_ID
      - FIREBASE_SVC_ACCOUNT_CLIENT_X509_CERT_URL
      - FIREBASE_STORAGE_DEFAULT_BUCKET
    # env_file:
    #   - ./.env
  db-test:
    container_name: cas_db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB_TEST
    # env_file:
    #   - ./.env