"""Added default column

Revision ID: 6d3ed0c1b66e
Revises: 8298e2141907
Create Date: 2022-08-14 00:54:06.072893

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d3ed0c1b66e"
down_revision = "8298e2141907"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "branches",
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("False"), nullable=True
        ),
    )
    op.add_column(
        "concerns",
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("False"), nullable=True
        ),
    )
    op.add_column(
        "goals",
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("False"), nullable=True
        ),
    )
    op.add_column(
        "access_types",
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("False"), nullable=True
        ),
    )
    op.add_column(
        "transportation_methods",
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("False"), nullable=True
        ),
    )
    op.execute("UPDATE branches SET is_default = true")
    op.execute("UPDATE concerns SET is_default = true")
    op.execute("UPDATE goals SET is_default = true")
    op.execute("UPDATE access_types SET is_default = true")
    op.execute("UPDATE transportation_methods SET is_default = true")
    op.alter_column("branches", "is_default", nullable=False)
    op.alter_column("concerns", "is_default", nullable=False)
    op.alter_column("goals", "is_default", nullable=False)
    op.alter_column("access_types", "is_default", nullable=False)
    op.alter_column("transportation_methods", "is_default", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transportation_methods", "is_default")
    op.drop_column("access_types", "is_default")
    op.drop_column("goals", "is_default")
    op.drop_column("concerns", "is_default")
    op.drop_column("branches", "is_default")
    # ### end Alembic commands ###
