"""Update caregiver and intake enums

Revision ID: 7343e3f6ce2b
Revises: ccabdb62cbef
Create Date: 2022-09-25 16:52:01.734435

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7343e3f6ce2b"
down_revision = "ccabdb62cbef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE intakes_first_nation_heritage AS ENUM('FIRST_NATION_REGISTERED','ELIGIBLE_FOR_REGISTRATION','INUIT','METIS','UNKNOWN')"
    )

    op.add_column(
        "intakes",
        sa.Column(
            "first_nation_heritage",
            sa.Enum(
                name="intakes_first_nation_heritage",
            ),
            nullable=True,
        ),
    )

    op.execute("ALTER TYPE intakes_court_status RENAME TO intakes_court_status_old")
    op.execute(
        "CREATE TYPE intakes_court_status AS ENUM('INTERIM_CARE','FINAL_ORDER_FOR_SOCIETY_CARE','EXTENDED_SOCIETY_CARE','SUPERVISION_ORDER','KIN_SERVICE_PLACEMENT','LIVING_WITH_BIO_FAMILY','OTHER')"
    )
    op.execute(
        "ALTER TABLE intakes ALTER COLUMN court_status TYPE intakes_court_status USING court_status::text::intakes_court_status"
    )
    op.execute("DROP TYPE intakes_court_status_old")

    op.execute(
        "ALTER TYPE caregivers_relationship_to_child RENAME TO caregivers_relationship_to_child_old"
    )
    op.execute(
        "CREATE TYPE caregivers_relationship_to_child AS ENUM('FOSTER_CAREGIVER','KINSHIP_CAREGIVER','BIOLOGICAL_FAMILY')"
    )
    op.execute(
        "ALTER TABLE caregivers ALTER COLUMN relationship_to_child TYPE caregivers_relationship_to_child USING relationship_to_child::text::caregivers_relationship_to_child"
    )
    op.execute("DROP TYPE caregivers_relationship_to_child_old")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intakes", "first_nation_heritage")
    op.execute("DROP TYPE intakes_first_nation_heritage")

    op.execute("ALTER TYPE intakes_court_status RENAME TO intakes_court_status_old")
    op.execute("CREATE TYPE intakes_court_status AS ENUM('APPROVED')")
    op.execute(
        "ALTER TABLE intakes ALTER COLUMN court_status TYPE intakes_court_status USING court_status::text::intakes_court_status"
    )
    op.execute("DROP TYPE intakes_court_status_old")

    op.execute(
        "ALTER TYPE caregivers_relationship_to_child RENAME TO caregivers_relationship_to_child_old"
    )
    op.execute(
        "CREATE TYPE caregivers_relationship_to_child AS ENUM('MOM','DAD','FOSTER_MOM','FOSTER_DAD','GRANDPARENT')"
    )
    op.execute(
        "ALTER TABLE caregivers ALTER COLUMN relationship_to_child TYPE caregivers_relationship_to_child USING relationship_to_child::text::caregivers_relationship_to_child"
    )
    op.execute("DROP TYPE caregivers_relationship_to_child_old")
    # ### end Alembic commands ###
