"""update intake model

Revision ID: 384228d16704
Revises: 94d5d0cd2d69
Create Date: 2022-11-02 16:29:06.489406

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "384228d16704"
down_revision = "94d5d0cd2d69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("intakes_goals")
    op.drop_table("intakes_concerns")

    # https://stackoverflow.com/questions/37848815/sqlalchemy-postgresql-enum-does-not-create-type-on-db-migrate
    cpin_file_type = postgresql.ENUM("INVESTIGATION", "ONGOING", name="cpin_file_type")
    cpin_file_type.create(op.get_bind())
    op.add_column(
        "intakes",
        sa.Column(
            "cpin_file_type",
            sa.Enum("INVESTIGATION", "ONGOING", name="cpin_file_type"),
            nullable=False,
        ),
    )

    # https://stackoverflow.com/questions/37848815/sqlalchemy-postgresql-enum-does-not-create-type-on-db-migrate
    intake_status = postgresql.ENUM(
        "IN PROGRESS", "IN REVIEW", "ACCEPTED", "DENIED", name="intake_status"
    )
    intake_status.create(op.get_bind())
    op.add_column(
        "intakes",
        sa.Column(
            "intake_status",
            sa.Enum(
                "IN PROGRESS", "IN REVIEW", "ACCEPTED", "DENIED", name="intake_status"
            ),
            nullable=True,
        ),
    )

    op.add_column(
        "intakes", sa.Column("referring_worker_contact", sa.String(), nullable=False)
    )
    op.add_column(
        "intakes", sa.Column("referring_worker_name", sa.String(), nullable=False)
    )
    op.add_column(
        "intakes", sa.Column("transportation_method", sa.String(), nullable=False)
    )
    op.add_column("intakes", sa.Column("user_id", sa.Integer(), nullable=True))
    op.alter_column(
        "intakes", "access_start_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "intakes", "access_type", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_constraint(
        "intakes_referring_worker_id_fkey", "intakes", type_="foreignkey"
    )
    op.create_foreign_key(None, "intakes", "users", ["user_id"], ["id"])
    op.drop_column("intakes", "transportation")
    op.drop_column("intakes", "court_order")
    op.drop_column("intakes", "is_ongoing")
    op.drop_column("intakes", "limitations")
    op.drop_column("intakes", "is_accepted")
    op.drop_column("intakes", "case_date")
    op.drop_column("intakes", "is_first_nation_heritage")
    op.drop_column("intakes", "referring_worker_id")
    op.drop_column("intakes", "is_investigation")
    op.drop_column("intakes", "is_court_involved")
    op.drop_column("intakes", "family_strengths")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intakes",
        sa.Column("family_strengths", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "intakes",
        sa.Column(
            "is_court_involved", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "intakes",
        sa.Column("is_investigation", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "intakes",
        sa.Column(
            "referring_worker_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "intakes",
        sa.Column(
            "is_first_nation_heritage", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "intakes", sa.Column("case_date", sa.DATE(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "intakes",
        sa.Column("is_accepted", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "intakes",
        sa.Column("limitations", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "intakes",
        sa.Column("is_ongoing", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "intakes",
        sa.Column("court_order", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "intakes",
        sa.Column("transportation", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "intakes", type_="foreignkey")
    op.create_foreign_key(
        "intakes_referring_worker_id_fkey",
        "intakes",
        "users",
        ["referring_worker_id"],
        ["id"],
    )
    op.alter_column("intakes", "access_type", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "intakes", "access_start_date", existing_type=sa.DATE(), nullable=True
    )
    op.drop_column("intakes", "user_id")
    op.drop_column("intakes", "transportation_method")
    op.drop_column("intakes", "referring_worker_name")
    op.drop_column("intakes", "referring_worker_contact")
    op.drop_column("intakes", "intake_status")
    op.drop_column("intakes", "cpin_file_type")
    op.create_table(
        "intakes_goals",
        sa.Column("intake_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("goal_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "start_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["goal_id"], ["goals.id"], name="intakes_goals_goal_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["intake_id"], ["intakes.id"], name="intakes_goals_intake_id_fkey"
        ),
    )
    op.create_table(
        "intakes_concerns",
        sa.Column("intake_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("concern_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["concern_id"], ["concerns.id"], name="intakes_concerns_concern_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["intake_id"], ["intakes.id"], name="intakes_concerns_intake_id_fkey"
        ),
    )
    # ### end Alembic commands ###
