"""update familial_concern and child_behavior

Revision ID: df6f80e55248
Revises: 12e97fac48b2
Create Date: 2022-11-11 23:30:38.982452

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "df6f80e55248"
down_revision = "12e97fac48b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_behaviors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("behavior", sa.String(), nullable=False),
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("False"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "familial_concerns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concern", sa.String(), nullable=False),
        sa.Column(
            "is_default", sa.Boolean(), server_default=sa.text("False"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "child_join_child_behavior",
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.Column("child_behavior_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_behavior_id"],
            ["child_behaviors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
    )
    op.drop_constraint(
        "intakes_concerns_concern_id_fkey", "intakes_concerns", type_="foreignkey"
    )
    op.drop_table("concerns")
    op.create_foreign_key(
        None, "intakes_concerns", "familial_concerns", ["concern_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "intakes_concerns", type_="foreignkey")
    op.create_foreign_key(
        "intakes_concerns_concern_id_fkey",
        "intakes_concerns",
        "concerns",
        ["concern_id"],
        ["id"],
    )
    op.create_table(
        "concerns",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM(
                "FAMILIAL_CONCERN", "CHILD_BEHAVIOUR", name="concerns_type"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("concern", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "is_default",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="concerns_pkey"),
    )
    op.drop_table("child_join_child_behavior")
    op.drop_table("familial_concerns")
    op.drop_table("child_behaviors")
    # ### end Alembic commands ###
