"""Create intake goals association table

Revision ID: 8298e2141907
Revises: 57f14d8ff8bf
Create Date: 2022-07-17 16:22:16.826045

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8298e2141907"
down_revision = "57f14d8ff8bf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intakes_goals",
        sa.Column("intake_id", sa.Integer(), nullable=True),
        sa.Column("goal_id", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["goal_id"],
            ["goals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["intake_id"],
            ["intakes.id"],
        ),
    )
    op.alter_column(
        "goals",
        "type",
        existing_type=postgresql.ENUM("SHORT_TERM", "LONG_TERM", name="goals_type"),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "goals",
        "type",
        existing_type=postgresql.ENUM("SHORT_TERM", "LONG_TERM", name="goals_type"),
        nullable=True,
    )
    op.drop_table("intakes_goals")
    # ### end Alembic commands ###
