"""remove address table

Revision ID: 5fff1dc51c07
Revises: 94d5d0cd2d69
Create Date: 2022-11-02 03:45:09.921896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5fff1dc51c07"
down_revision = "94d5d0cd2d69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("daytime_contacts", sa.Column("address", sa.String(), nullable=False))
    op.drop_constraint(
        "daytime_contacts_address_id_fkey", "daytime_contacts", type_="foreignkey"
    )
    op.drop_column("daytime_contacts", "address_id")
    op.add_column("intakes", sa.Column("access_location", sa.String(), nullable=True))
    op.drop_constraint("intakes_access_location_id_fkey", "intakes", type_="foreignkey")
    op.drop_column("intakes", "access_location_id")
    op.drop_table("addresses")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intakes",
        sa.Column(
            "access_location_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        "intakes_access_location_id_fkey",
        "intakes",
        "addresses",
        ["access_location_id"],
        ["id"],
    )
    op.drop_column("intakes", "access_location")
    op.add_column(
        "daytime_contacts",
        sa.Column("address_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "daytime_contacts_address_id_fkey",
        "daytime_contacts",
        "addresses",
        ["address_id"],
        ["id"],
    )
    op.drop_column("daytime_contacts", "address")
    op.create_table(
        "addresses",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("street_address", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("postal_code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "latitude",
            sa.NUMERIC(precision=8, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "longitude",
            sa.NUMERIC(precision=9, scale=6),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="addresses_pkey"),
    )
    # ### end Alembic commands ###
