"""modify child service worker

Revision ID: bb23310db98a
Revises: 784b7a2d1114
Create Date: 2023-04-05 22:58:08.214445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb23310db98a"
down_revision = "784b7a2d1114"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("children", sa.Column("service_worker", sa.String(), nullable=False))
    op.drop_constraint(
        "children_child_service_worker_id_fkey", "children", type_="foreignkey"
    )
    op.drop_column("children", "child_service_worker_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "children",
        sa.Column(
            "child_service_worker_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "children_child_service_worker_id_fkey",
        "children",
        "users",
        ["child_service_worker_id"],
        ["id"],
    )
    op.drop_column("children", "service_worker")
    # ### end Alembic commands ###
