"""fix attendance model typos

Revision ID: 784b7a2d1114
Revises: f6669088b3f1
Create Date: 2023-03-02 05:16:56.522409

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "784b7a2d1114"
down_revision = "f6669088b3f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_records",
        sa.Column("child_family_support_worker_id", sa.Integer(), nullable=True),
    )
    op.drop_constraint(
        "attendance_records_child_family_suypport_worker_id_fkey",
        "attendance_records",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "attendance_records", "users", ["child_family_support_worker_id"], ["id"]
    )
    op.drop_column("attendance_records", "child_family_suypport_worker_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_records",
        sa.Column(
            "child_family_suypport_worker_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "attendance_records", type_="foreignkey")
    op.create_foreign_key(
        "attendance_records_child_family_suypport_worker_id_fkey",
        "attendance_records",
        "users",
        ["child_family_suypport_worker_id"],
        ["id"],
    )
    op.drop_column("attendance_records", "child_family_support_worker_id")
    # ### end Alembic commands ###
