"""added lead_access_worker_name and intake_meeting_notes

Revision ID: 9674564fde8d
Revises: e5d9b1c73228
Create Date: 2023-06-11 16:38:45.286561

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9674564fde8d"
down_revision = "e5d9b1c73228"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intakes", sa.Column("intake_meeting_notes", sa.String(), nullable=True)
    )
    op.add_column(
        "intakes", sa.Column("lead_access_worker_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("intakes", "lead_access_worker_name")
    op.drop_column("intakes", "intake_meeting_notes")
    # ### end Alembic commands ###
