"""fixing daytime contact and child relation

Revision ID: 85753f37ce63
Revises: 3df009c5afd2
Create Date: 2023-11-28 04:09:25.481353

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85753f37ce63"
down_revision = "3df009c5afd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "daytime_contacts_child_id_fkey", "daytime_contacts", type_="foreignkey"
    )
    op.drop_column("daytime_contacts", "child_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daytime_contacts",
        sa.Column("child_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "daytime_contacts_child_id_fkey",
        "daytime_contacts",
        "children",
        ["child_id"],
        ["id"],
    )
    # ### end Alembic commands ###
