"""Fix transportation typo

Revision ID: 4df756383780
Revises: c08705245bb9
Create Date: 2023-11-28 03:26:29.962052

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4df756383780"
down_revision = "c08705245bb9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transportation",
        sa.Column("attendance_record_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "transportation_attendence_record_id_fkey", "transportation", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "transportation", "attendance_records", ["attendance_record_id"], ["id"]
    )
    op.drop_column("transportation", "attendence_record_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transportation",
        sa.Column(
            "attendence_record_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "transportation", type_="foreignkey")
    op.create_foreign_key(
        "transportation_attendence_record_id_fkey",
        "transportation",
        "attendance_records",
        ["attendence_record_id"],
        ["id"],
    )
    op.drop_column("transportation", "attendance_record_id")
    # ### end Alembic commands ###
