"""change child model

Revision ID: a52b5c1d2560
Revises: 2e3a95429cdf
Create Date: 2023-11-28 03:14:50.318550

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a52b5c1d2560"
down_revision = "2e3a95429cdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("children", sa.Column("name", sa.String(), nullable=False))
    op.drop_column("children", "first_name")
    op.drop_column("children", "last_name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "children",
        sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "children",
        sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("children", "name")
    # ### end Alembic commands ###
