"""Change child provider relationship

Revision ID: 142c528373ea
Revises: db7c2f31d3ea
Create Date: 2023-12-05 00:58:54.363918

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "142c528373ea"
down_revision = "db7c2f31d3ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_providers",
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.Column("providers_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.ForeignKeyConstraint(
            ["providers_id"],
            ["providers.id"],
        ),
    )
    op.add_column("providers", sa.Column("intake_id", sa.Integer(), nullable=True))
    op.drop_constraint("providers_child_id_fkey", "providers", type_="foreignkey")
    op.create_foreign_key(None, "providers", "intakes", ["intake_id"], ["id"])
    op.drop_column("providers", "child_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers",
        sa.Column("child_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "providers", type_="foreignkey")
    op.create_foreign_key(
        "providers_child_id_fkey", "providers", "children", ["child_id"], ["id"]
    )
    op.drop_column("providers", "intake_id")
    op.drop_table("child_providers")
    # ### end Alembic commands ###
