"""remove

Revision ID: e5d9b1c73228
Revises: 3c7ee24004d0
Create Date: 2023-06-01 05:12:02.004664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e5d9b1c73228"
down_revision = "3c7ee24004d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "attendance_sheets_intake_id_fkey", "attendance_sheets", type_="foreignkey"
    )
    op.drop_column("intakes", "access_time")
    op.drop_column("intakes", "access_weekday")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intakes",
        sa.Column(
            "access_weekday",
            postgresql.ARRAY(
                postgresql.ENUM(
                    "MONDAY",
                    "TUESDAY",
                    "WEDNESDAY",
                    "THURSDAY",
                    "FRIDAY",
                    "SATURDAY",
                    "SUNDAY",
                    name="intakes_access_weekday",
                )
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "intakes",
        sa.Column("access_time", postgresql.TIME(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "attendance_sheets_intake_id_fkey",
        "attendance_sheets",
        "intakes",
        ["intake_id"],
        ["id"],
    )
    # ### end Alembic commands ###
