"""update caregiver relationship enum part 1

Revision ID: 696af69c44f7
Revises: 9403ac64967a
Create Date: 2023-12-12 03:33:13.142747

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "696af69c44f7"
down_revision = "9403ac64967a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("caregivers", "relationship_to_child")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "caregivers",
        sa.Column(
            "relationship_to_child",
            postgresql.ENUM(
                "FOSTER_CAREGIVER",
                "KINSHIP_CAREGIVER",
                "BIOLOGICAL_FAMILY",
                name="caregivers_relationship_to_child",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
