"""<short description of the migration>

Revision ID: aaa476e7d168
Revises: 752ae3a1854f
Create Date: 2023-11-21 02:29:59.290285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "aaa476e7d168"
down_revision = "752ae3a1854f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "visit_cadences", "caregiver_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "visit_cadences", "caregiver_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
