"""change attendance sheet and record model column names

Revision ID: f6669088b3f1
Revises: 823354eaef0b
Create Date: 2023-02-24 04:17:41.827535

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f6669088b3f1"
down_revision = "823354eaef0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_records",
        sa.Column("child_family_suypport_worker_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "attendance_records", sa.Column("location", sa.String(), nullable=False)
    )
    op.drop_constraint(
        "attendance_records_access_worker_id_fkey",
        "attendance_records",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "attendance_records", "users", ["child_family_suypport_worker_id"], ["id"]
    )
    op.drop_column("attendance_records", "place")
    op.drop_column("attendance_records", "access_worker_id")
    op.add_column("attendance_sheets", sa.Column("csw", sa.String(), nullable=False))
    op.add_column("attendance_sheets", sa.Column("fcc", sa.String(), nullable=False))
    op.drop_column("attendance_sheets", "cic")
    op.drop_column("attendance_sheets", "riv")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance_sheets",
        sa.Column("riv", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "attendance_sheets",
        sa.Column("cic", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("attendance_sheets", "fcc")
    op.drop_column("attendance_sheets", "csw")
    op.add_column(
        "attendance_records",
        sa.Column("access_worker_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "attendance_records",
        sa.Column("place", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "attendance_records", type_="foreignkey")
    op.create_foreign_key(
        "attendance_records_access_worker_id_fkey",
        "attendance_records",
        "users",
        ["access_worker_id"],
        ["id"],
    )
    op.drop_column("attendance_records", "location")
    op.drop_column("attendance_records", "child_family_suypport_worker_id")
    # ### end Alembic commands ###
