"""change child-provider relationship

Revision ID: 05393a9f6f23
Revises: 2e3a95429cdf
Create Date: 2023-11-11 18:52:37.274933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "05393a9f6f23"
down_revision = "2e3a95429cdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_providers",
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.Column("providers_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
        sa.ForeignKeyConstraint(
            ["providers_id"],
            ["providers.id"],
        ),
    )
    op.add_column("providers", sa.Column("intake_id", sa.Integer(), nullable=True))
    op.drop_constraint("providers_child_id_fkey", "providers", type_="foreignkey")
    op.create_foreign_key(None, "providers", "intakes", ["intake_id"], ["id"])
    op.drop_column("providers", "child_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "providers",
        sa.Column("child_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "providers", type_="foreignkey")
    op.create_foreign_key(
        "providers_child_id_fkey", "providers", "children", ["child_id"], ["id"]
    )
    op.drop_column("providers", "intake_id")
    op.drop_table("child_providers")
    # ### end Alembic commands ###
