"""Add visitor_relationship

Revision ID: 7cec03c12282
Revises: 76cae4bc58da
Create Date: 2023-12-07 02:28:18.313795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7cec03c12282"
down_revision = "76cae4bc58da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visiting_members",
        sa.Column(
            "visitor_relationship",
            sa.Enum(
                "FOSTER_CAREGIVER",
                "KINSHIP_CAREGIVER",
                "BIOLOGICAL_FAMILY",
                "ADOPTIVE_PARENT",
                "FOSTER_PARENT",
                "BIOLOGICAL_PARENT",
                "STEP_PARENT",
                "MATERNAL_GRANDPARENT",
                "PATERNAL_GRANDPARENT",
                "SIBLING",
                "STEP_SIBLING",
                "HALF_SIBLING",
                "UNCLE/AUNT",
                "OTHER_RELATIVE",
                "OTHER",
                name="visitorRelationship",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visiting_members", "visitor_relationship")
    # ### end Alembic commands ###
