"""Update attendance model

Revision ID: 76cae4bc58da
Revises: c08705245bb9
Create Date: 2023-12-07 02:25:49.318979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "76cae4bc58da"
down_revision = "c08705245bb9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visiting_members", "visitor_relationship")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visiting_members",
        sa.Column(
            "visitor_relationship",
            postgresql.ENUM("MOM", "DAD", name="visitorRelationship"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
