"""update daytime contact with child id

Revision ID: bfd539ae9121
Revises: 839076ab9712
Create Date: 2023-12-14 01:57:12.423589

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfd539ae9121"
down_revision = "839076ab9712"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "children_daytime_contact_id_fkey", "children", type_="foreignkey"
    )
    op.drop_column("children", "daytime_contact_id")
    op.add_column(
        "daytime_contacts", sa.Column("child_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "daytime_contacts", "children", ["child_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "daytime_contacts", type_="foreignkey")
    op.drop_column("daytime_contacts", "child_id")
    op.add_column(
        "children",
        sa.Column(
            "daytime_contact_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "children_daytime_contact_id_fkey",
        "children",
        "daytime_contacts",
        ["daytime_contact_id"],
        ["id"],
    )
    # ### end Alembic commands ###
