"""Update attendance sheet fields

Revision ID: 9102ff64a1fd
Revises: ba551533e51d
Create Date: 2023-10-03 02:36:39.066166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9102ff64a1fd"
down_revision = "ba551533e51d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_child",
        sa.Column("attendance_sheets_id", sa.Integer(), nullable=True),
        sa.Column("child_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attendance_sheets_id"],
            ["attendance_sheets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["children.id"],
        ),
    )
    op.drop_column("attendance_sheets", "month")
    op.alter_column(
        "visit_cadences", "caregiver_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "visit_cadences", "child_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "visit_cadences", "child_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "visit_cadences", "caregiver_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.add_column(
        "attendance_sheets",
        sa.Column(
            "month",
            postgresql.ENUM(
                "JANUARY",
                "FEBRUARY",
                "MARCH",
                "APRIL",
                "MAY",
                "JUNE",
                "JULY",
                "AUGUST",
                "SEPTEMBER",
                "OCTOBER",
                "NOVEMBER",
                "DECEMBER",
                name="month",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("attendance_child")
    # ### end Alembic commands ###
