"""added model for visit cadence

Revision ID: 900a2298b0d2
Revises: 73b155c137af
Create Date: 2023-07-14 03:15:10.029336

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "900a2298b0d2"
down_revision = "73b155c137af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "visit_cadences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "date",
            sa.Enum(
                "Monday",
                "Tuesday",
                "wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday",
                name="visit_cadence_date",
            ),
            nullable=False,
        ),
        sa.Column("time", sa.String(), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum("Weekly", "Biweekly", "Monthly", name="visit_cadence_frequency"),
            nullable=False,
        ),
        sa.Column(
            "family_member",
            sa.Enum("Dad", "Mom", "Grandma", name="visit_cadence_family_member"),
            nullable=False,
        ),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("intake_id", sa.Integer(), nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["child_id"], ["children.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["intake_id"], ["intakes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("visit_cadences")
    # ### end Alembic commands ###
