"""remove kinship and foster placement from child

Revision ID: 58c30491ece7
Revises: 5142d62fc44e
Create Date: 2023-05-28 15:38:54.595947

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58c30491ece7"
down_revision = "5142d62fc44e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "children", "has_foster_placement", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "children", "has_kinship_provider", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "children", "has_kinship_provider", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "children", "has_foster_placement", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###
