"""update caregiver relationship enum part 2

Revision ID: d280938be955
Revises: 696af69c44f7
Create Date: 2023-12-12 03:34:24.602800

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d280938be955"
down_revision = "696af69c44f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "caregivers",
        sa.Column(
            "relationship_to_child",
            sa.Enum(
                "ADOPTIVE_PARENT",
                "BIOLOGICAL_PARENT",
                "STEP-PARENT",
                "MATERNAL_GRANDPARENT",
                "PATERNAL_GRANDPARENT",
                "SIBLING",
                "HALF_SIBLING",
                "STEP_SIBLING",
                "UNCLE/AUNT",
                "OTHER_RELATIVE",
                "OTHER",
                name="caregivers_relationship_to_child",
            ),
            nullable=False,
        ),
    )
    op.execute(
        "ALTER TYPE caregivers_relationship_to_child RENAME TO caregivers_relationship_to_child_old"
    )
    op.execute(
        "CREATE TYPE caregivers_relationship_to_child AS ENUM('ADOPTIVE_PARENT', 'BIOLOGICAL_PARENT', 'STEP-PARENT','MATERNAL_GRANDPARENT','PATERNAL_GRANDPARENT','SIBLING','HALF_SIBLING','STEP_SIBLING','UNCLE/AUNT','OTHER_RELATIVE','OTHER')"
    )
    op.execute(
        "ALTER TABLE caregivers ALTER COLUMN relationship_to_child TYPE caregivers_relationship_to_child USING relationship_to_child::text::caregivers_relationship_to_child"
    )
    op.execute("DROP TYPE caregivers_relationship_to_child_old")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(
        "ALTER TYPE caregivers_relationship_to_child RENAME TO caregivers_relationship_to_child_old"
    )
    op.execute(
        "CREATE TYPE caregivers_relationship_to_child AS ENUM('FOSTER_CAREGIVER','KINSHIP_CAREGIVER','BIOLOGICAL_FAMILY')"
    )
    op.execute(
        "ALTER TABLE caregivers ALTER COLUMN relationship_to_child TYPE caregivers_relationship_to_child USING relationship_to_child::text::caregivers_relationship_to_child"
    )
    op.execute("DROP TYPE caregivers_relationship_to_child_old")
    op.drop_column("caregivers", "relationship_to_child")
    # ### end Alembic commands ###
