"""add pdf_file table, add court_order_file fk to intakes table

Revision ID: bfc8a3a17d73
Revises: 839076ab9712
Create Date: 2024-02-04 18:46:26.447781

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bfc8a3a17d73"
down_revision = "839076ab9712"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdf_file",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_data", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "intakes", sa.Column("court_order_file_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, "intakes", "pdf_file", ["court_order_file_id"], ["id"])
    op.drop_column("intakes", "court_order_file")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intakes",
        sa.Column(
            "court_order_file", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "intakes", type_="foreignkey")
    op.drop_column("intakes", "court_order_file_id")
    op.drop_table("pdf_file")
    # ### end Alembic commands ###
