"""add pdf file table

Revision ID: 13ae9bdfae49
Revises: 839076ab9712
Create Date: 2024-02-08 02:03:18.220687

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "13ae9bdfae49"
down_revision = "839076ab9712"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdf_file",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("file_data", postgresql.BYTEA(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pdf_file")
    # ### end Alembic commands ###
