"""add pdf file connection to intakes

Revision ID: 40c337ae90da
Revises: 13ae9bdfae49
Create Date: 2024-02-08 02:19:09.025524

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40c337ae90da"
down_revision = "13ae9bdfae49"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intakes", sa.Column("court_order_file_id", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE intakes SET court_order_file_id = 1")
    op.alter_column("intakes", "court_order_file_id", nullable=False)

    op.create_foreign_key(None, "intakes", "pdf_file", ["court_order_file_id"], ["id"])
    op.drop_column("intakes", "court_order_file")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intakes",
        sa.Column(
            "court_order_file", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "intakes", type_="foreignkey")
    op.drop_column("intakes", "court_order_file_id")
    # ### end Alembic commands ###
