"""update

Revision ID: caf7451544a3
Revises: 839076ab9712
Create Date: 2024-02-20 23:36:12.368672

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "caf7451544a3"
down_revision = "839076ab9712"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pdf_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("file_data", postgresql.BYTEA(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "intakes", sa.Column("court_order_file_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "intakes", "pdf_files", ["court_order_file_id"], ["id"])
    op.drop_column("intakes", "court_order_file")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "intakes",
        sa.Column(
            "court_order_file", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "intakes", type_="foreignkey")
    op.drop_column("intakes", "court_order_file_id")
    op.drop_table("pdf_files")
    # ### end Alembic commands ###
