"""Create daytime_contact model

Revision ID: 4dfecb9b3a37
Revises: 1f9c523fe04c
Create Date: 2022-06-17 17:29:58.065826

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4dfecb9b3a37"
down_revision = "1f9c523fe04c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daytime_contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("contact_first_name", sa.String(), nullable=False),
        sa.Column("contact_last_name", sa.String(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("SCHOOL", "DAYCARE", name="daytime_contacts_type"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["address_id"],
            ["addresses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daytime_contacts")
    op.execute("DROP TYPE daytime_contacts_type")
    # ### end Alembic commands ###
