"""Create transportation_method model

Revision ID: 5c95f4efed2d
Revises: 8a03057d5a04
Create Date: 2022-06-05 16:08:35.285100

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import table

# revision identifiers, used by Alembic.
revision = "5c95f4efed2d"
down_revision = "8a03057d5a04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    transportation_methods = op.create_table(
        "transportation_methods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transportation_method", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.bulk_insert(
        transportation_methods,
        [
            {"transportation_method": "Agency Driver"},
            {"transportation_method": "Kin Provider"},
            {"transportation_method": "Foster Parent"},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transportation_methods")
    # ### end Alembic commands ###
