"""Reference user branch using lookup table

Revision ID: 6cd80740889b
Revises: 8a03057d5a04
Create Date: 2022-06-09 00:54:26.467547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6cd80740889b"
down_revision = "8a03057d5a04"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("branch", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column('branch_id', sa.Integer(), sa.ForeignKey('branches.id')))
    op.execute("INSERT INTO branches (branch) VALUES ('Algoma')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "branch_id")
    op.drop_table("branches")
    # ### end Alembic commands ###
