"""Create access_types model

Revision ID: 7036da15285b
Revises: 797bfedc3a06
Create Date: 2022-06-09 00:45:26.144213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7036da15285b"
down_revision = "797bfedc3a06"
branch_labels = None
depends_on = None


def upgrade():
    access_types = op.create_table(
        "access_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(access_types,
    [
            {'id':1, 'access_type':'Twice Weekly'},
            {'id':2, 'access_type':'Weekly, Any Time'},
            {'id':3, 'access_type':'Weekly, After School'},
            {'id':4, 'access_type':'Virtual'}
        ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_types")
    # ### end Alembic commands ###
