"""Create access_types model

Revision ID: 7036da15285b
Revises: 5c95f4efed2d
Create Date: 2022-06-09 00:45:26.144213

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7036da15285b"
down_revision = "5c95f4efed2d"
branch_labels = None
depends_on = None


def upgrade():
    access_types = op.create_table(
        "access_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(
        access_types,
        [
            {"id": 1, "access_type": "TWICE WEEKLY"},
            {"id": 2, "access_type": "WEEKLY, ANY TIME"},
            {"id": 3, "access_type": "WEEKLY, AFTER SCHOOL"},
            {"id": 4, "access_type": "VIRTUAL"},
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("access_types")
    # ### end Alembic commands ###
